export const InternalError = (): string => {
  return `Erro interno inesperado aconteceu ao tentar interagir com métodos de nossa aplicação!`
}
